point docs to core docs site (Close #119)
snowplow/dbt-snowplow-web pull request #120
Opened 2022-10-10 11:03 UTC by rlh1994

## Description & motivation
Remove most of the docs that are now on core docs and point to core docs site.

DO NOT MERGE until https://github.com/snowplow/documentation/pull/113 has been closed 

## Checklist
- [x] I have verified that these changes work locally
- [x] I have updated the README.md (if applicable)
- [x] I have added tests & descriptions to my models (and macros if applicable)

2022-10-10 11:04 UTC, snowplowcla commented
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://docs.snowplowanalytics.com/docs/contributing/contributor-license-agreement/ to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

2022-10-14 18:43 UTC, paulboocock approved these changes

2022-10-14 18:45 UTC, paulboocock requested changes
Changed my mind ;-)

2022-10-14 18:45 UTC, paulboocock commented on docs/markdown/snowplow_web_overview.md
> +**For more information, including a QuickStart guide, operation and configuration, and implementing your own custom modules on top of this please visit the [Snowplow Docs](https://docs.snowplowanalyt
```suggestion
**For more information, including a QuickStart guide, operation and configuration, and implementing your own custom modules on top of this please visit the [Snowplow Docs](https://docs.snowplow.io/docs/modeling-your-data/modeling-your-data-with-dbt/).**
```

2022-10-14 21:30 UTC, rlh1994 commented on docs/markdown/snowplow_web_overview.md
> +**For more information, including a QuickStart guide, operation and configuration, and implementing your own custom modules on top of this please visit the [Snowplow Docs](https://docs.snowplowanalyt
Replaced all instances to snowplow.io

2022-10-18 12:43 UTC, paulboocock approved these changes

2022-10-18 13:23 UTC, merged