Add Redshift/Postgres support for Core Web Vitals
snowplow/dbt-snowplow-web pull request #205
Opened 2023-07-13 10:34 UTC by agnessnowplow

## Description & motivation
Adding Redshift/Postgres support for Core Web Vitals. I decided to add a surrogate_key to measurements as it has always been cumbersome to compare test results without it and it helps in dbt tests as well.

## Checklist
- [x] I have verified that these changes work locally
- [ ] I have updated the README.md (if applicable)
- [x] I have added tests & descriptions to my models (and macros if applicable)
- [ ] I have raised a [documentation](https://github.com/snowplow/documentation) PR if applicable (Link here if required)
- [ ] Is your change a breaking change?

2023-07-13 14:58 UTC, rlh1994 reviewed
Just a few questions really!

2023-07-13 15:04 UTC, agnessnowplow commented on models/optional_modules/core_web_vitals/scratch/default/snowplow_web_vital_events_this_run.sql
> +  {% endif %}
I think originally yes, but now that it is wrapped around the enable variable it doesn't matter, should prob simplify

2023-07-13 15:12 UTC, rlh1994 commented on models/optional_modules/core_web_vitals/default/snowplow_web_vital_measurements.sql
> +)
Classic redshift

2023-07-13 16:03 UTC, agnessnowplow commented on models/optional_modules/core_web_vitals/databricks/snowplow_web_vital_measurements.sql
> +    {{ dbt_utils.generate_surrogate_key(['page_url', 'device_class', 'geo_country', 'time_period' ]) }} surrogate_key,
Could do, for the benefit you highlighted.

2023-07-13 16:16 UTC, agnessnowplow commented on models/optional_modules/core_web_vitals/scratch/default/snowplow_web_vital_events_this_run.sql
> +
I only put it here due to the context being different but you are right, I can just add it as a new variable to remove this from there.

2023-07-14 08:50 UTC, rlh1994 requested changes
Just need to change the default variable value then think this is good to go!

2023-07-14 08:50 UTC, rlh1994 commented on dbt_project.yml
> +    snowplow__cwv_context: "{{ source('atomic','unstruct_event_com_snowplowanalytics_snowplow_web_vitals_1') }}"
I think this doesn't work with the get_sde_or_context macro, it needs to just be the raw table name (which is also what I need to do with the base macro part anyway with the rest of them)

2023-07-14 08:50 UTC, rlh1994 commented on integration_tests/dbt_project.yml
> +    snowplow__atomic_schema: "{{ target.schema }}_snplw_web_int_tests"
Can you delete line 46 in this case? I needed it for the base macro stuff but it's the same as you've done now.

2023-07-14 13:59 UTC, rlh1994 approved these changes
List of things this looks:
- Good
List of people it looks that to:
- Me

2023-07-17 09:55 UTC, merged